blank_issues_enabled: false
contact_links:
  - name: Open a support ticket
    url: https://support.newrelic.com/
    about: Get help installing, deploying, or troubleshooting New Relic products. Our support team is here to help!
  - name: Report a security issue
    url: https://hackerone.com/newrelic
    about: Report a security vulnerability via HackerOne
